### ISSUE TITLE
Setting the country_code

### ISSUE THREAD

**Issue by moonilightshaker** [sclaflin/Plate-Minder#11]
Hi,
can i set the country_code in the Plate-Minder configuration?
I have not found this.
With the USA setting, some license plates are not detected. With the EU setting it works fine. (I am from Austria)

Thanks

**Comment by sclaflin** [comment]
Yup, looks like an oversight.  I'll see about getting this supported.

**Comment by Machu95** [comment]
Hi, can i change country code manualy for now?

**Comment by bafplus** [comment]
Any news with defining the country code?

**Comment by sclaflin** [comment]
Apologies for the long delay. Country codes should now be supported. Details are included in the README for this project.

**Comment by bafplus** [comment]
Thanks you so very much!
