### ISSUE TITLE
Plate Minder Crashes when two License Plates are in frame

### ISSUE THREAD

**Issue by adam-armani** [sclaflin/Plate-Minder#15]
Plate Minder Crashes when two License Plates are in frame. Deployment Environment is Synology DS918+ Docker.

**Comment by sclaflin** [comment]
Any chance you could provide an error message or an example?

**Comment by adam-armani** [comment]
![plate-minder-error](https://user-images.githubusercontent.com/55850595/190261236-27ca7b30-5eed-4123-a315-5c279da6b2c0.jpg)
[plate-minder.csv](https://github.com/sclaflin/Plate-Minder/files/9569907/plate-minder.csv)

Check the error message

**Comment by sclaflin** [comment]
This is a nearly 17MB file. I'm not going to hunt through it to find an error.  Please provide an example, the specific error, or anything else that can help me reproduce your issue to fix it.
