### ISSUE TITLE
Question about `matches_template`

### ISSUE THREAD

**Issue by KidA001** [sclaflin/Plate-Minder#19]
First off I'd like to say thank you for creating this. I was able to get it up and running (and most importantly working) in very little time.

I have a question about the `matches_template` key in the MQTT results. I'm wondering where this comes from. I guess I'm curious if I can feed it a list of know/common license plates I expect or if I'm completely off here.

Thanks again!

**Comment by sclaflin** [comment]
Hey! Happy you got it running!

That's output coming directly from OpenALPR. Here's a link describing what it means:

https://github.com/openalpr/openalpr/wiki/OpenALPR-Design#post-processing

**Comment by KidA001** [comment]
Is it possible to allow us to pass an arg `--pattern <pattern code>` (a state) to OpenAlpr?

**Comment by sclaflin** [comment]
Not currently, no. But it's likely a useful feature to implement.

**Comment by KidA001** [comment]
@sclaflin put up a PR, would love your feedback
https://github.com/sclaflin/Plate-Minder/pull/21

**Comment by sclaflin** [comment]
Nice! I'll give it a look shortly.

**Comment by KidA001** [comment]
@sclaflin thanks for merging! Does this automatically deploy changes to both docker builds as `:latest`?

**Comment by sclaflin** [comment]
Not "automatic" but, yes. :)

**Comment by KidA001** [comment]
Sweet. Just wondering when I can pull the new images. I saw you mentioned you were working on the size of the build for `OpenALPR-HTTP-Wrapper` so wasn't sure the timing on that. I see both images are updated on Docker recently so just assuming those contain the new changes

Thanks again!
