### ISSUE TITLE
Cannot apply filters

### ISSUE THREAD

**Issue by fokcuk** [sclaflin/Plate-Minder#2]
When filters are enabled in the config (to remove time stamp detection or to only detect motion) I get errors in processing:

Shapes:
plate-minder              | abort(YAMLSyntaxError: All collection items must start at the same column). Build with -s ASSERTIONS=1 for more info.
plate-minder              | (Use `node --trace-uncaught ...` to show where the exception was thrown)

Motion:
plate-minder              | abort(TypeError: Invalid MJPEGReadable type.). Build with -s ASSERTIONS=1 for more info.
plate-minder              | (Use `node --trace-uncaught ...` to show where the exception was thrown)

**Comment by fokcuk** [comment]
also I am not getting any plate captures post reinstall.
Is there a debug view to see how it tries to analyse it?

**Comment by sclaflin** [comment]
Can you include your config.yaml? That'd help with diagnosing the problems you're having.

**Comment by fokcuk** [comment]
After I have added RESTful API part in the config file it started to work.
https://github.com/sclaflin/Plate-Minder/blob/master/config.yaml does not have this section. Can you please review and update what is needed?
It is also missing the section to enable HA integration

**Comment by sclaflin** [comment]
Please refer to the documentation in the README rather than looking at files used for development.
If your intentions are to just use the software, everything you need to get up and running is in the README.md file.

**Comment by fokcuk** [comment]
I usually just do "git clone"
