### ISSUE TITLE
Understanding shape filter

### ISSUE THREAD

**Issue by KidA001** [sclaflin/Plate-Minder#20]
I'd like to create a mask so plate-minder can ignore a section of the camera. I don't quite understand the format here `1267,0,1920,0,1920,100,1267,100`.  I understand it's referencing the size of the image I am passing it in pixels. Is there a tool I can use to preview the mask?

**Comment by sclaflin** [comment]
It's poorly documented, but there's some explanation in the README.md at the root of this project:

```markdown
# Globally applied filters
# Filter jpeg frames. Currently 'motion' and 'mask' filters are available.
# Filters are processed in the order they are defined
filters:
  # Masks out a portion of the frame. Note that any pixels within the mask
  # cannot be used for detection.
  - type: mask
    # Optional. Outputs an image to the './data' path
    # debug: true
    shapes:
      # Shapes are a series of x/y coordinates
      - 1267,0,1920,0,1920,100,1267,100 # Timestamp, top right
  # Crops the frame down to the largest area of motion detection
  - type: motion
    # Optional. Outputs an image to the './data' path
    # debug: true
```

**Comment by KidA001** [comment]
I saw that, but I still don't understand what the end result is. Is this just a polygon that uses fill? Do the coords above create a rectangle with fill? i.e.
point 1: [1267,0] point 2: [1920,0] point 3: [100,1267]

And is 0,0 bottom left?

Is there any way for me to see the mask that it uses?

**Comment by KidA001** [comment]
Scratch that, I didn't realize the debug image in the web UI would display the shape. And for me `0,0` was top-left
