### ISSUE TITLE
I made a web interface for viewing the images

### ISSUE THREAD

**Issue by jfarre20** [sclaflin/Plate-Minder#23]
Using chatgpt and github copilot, I made a little interface for viewing the captured plates, feel free to use:

https://github.com/jfarre20/PlateFInder/

![image](https://user-images.githubusercontent.com/7387914/228707826-f2105221-48c3-4b37-b535-601e082f7a35.png)

**Comment by sclaflin** [comment]
That's pretty cool! 

I'd prefer to keep this to open issues with PlateMinder.
