### ISSUE TITLE
Disable Image in MQTT Request

### ISSUE THREAD

**Issue by KidA001** [sclaflin/Plate-Minder#26]
I'm trying to speed up requests and would like to disable the image sent to the MQTT request. Is there any option I'm missing to be able to do this without editing the repo?

**Comment by sclaflin** [comment]
Right now, MQTT support is either enabled or disabled. If you're looking for more granular support for MQTT, that would have to be added.

**Comment by KidA001** [comment]
I thought that might be the case....I haven't tested this PR yet and will run it this evening but how does this look?

https://github.com/sclaflin/Plate-Minder/pull/27 and https://github.com/sclaflin/Plate-Minder-Web/pull/1

**Comment by KidA001** [comment]
@sclaflin I can get `plate-minder` and `open-alpr-http-wrapper` to run and work together with my changes but I'm having trouble running `Plate-Minder Web` locally. Not because of code issues but just dependencies. For some reason I can't build locally (getting `parcel` errors) and if I use docker it immediately exists when I run the container that I built from `Dockerfile.dev`

**Comment by sclaflin** [comment]
These projects were developed within VS Code Dev Containers.  I'm sure you could get it running without VS Code, but that's the environment it was created in.

1. Install VS Code
2. Install the "Dev Containers" extension within VS Code.
3. Click the green "><" icon at the bottom left of VS Code and select "reopen in container"
4. From within the dev container, install npm dependencies "npm ci"
5. Press F5 to start a debug session. You'll see a warning about not being able to debug parcel, click "debug anyway".

**Comment by KidA001** [comment]
@sclaflin found my issue, I had some bad syntax that I corrected. I have it running in my terminal and also in VS Code now. Needed to add one more piece of config for plate-minder-web. It's all pushed up now and everything is working for me locally.

**Comment by sclaflin** [comment]
Closing this issue as the [pull request](https://github.com/sclaflin/Plate-Minder/pull/27) seems abandoned. Let me know there if you'd like to pursue this further.
