### ISSUE TITLE
Timezone setting?

### ISSUE THREAD

**Issue by wavecentral** [sclaflin/Plate-Minder#28]
Any thoughts on he ability to set the timezone via the config.yaml or inherit the localtime zone?

What I'm observing is that even though the system is set with US/Central for timezone, Plateminder runtime still uses UTC, which is the default, if NodeJS TZ is not set.

You could fetch it via several methods listed, and then use process.env.TZ to set it?

Perhaps make it a setting 'area' like so, that is selectable:

Timezone:  [ ] Default "UTC" [ ] System "US/Central"

Just some ideas...

**Comment by sclaflin** [comment]
Hey there,

You could try mounting the host's /etc/localtime as read-only. This is documented in the README.md file of this project.

**Comment by sclaflin** [comment]
You could also add a "TZ" environment variable to your container.

https://docs.docker.com/compose/environment-variables/set-environment-variables/

**Comment by wavecentral** [comment]
I somewhat had to workaround the /etc/localtime, as the system via cmd 'date' on the docker terminal returned UTC and with my work around below, the correct timezone was appearing, but the nodejs app still returns UTC time.  I injected the following in the checkEnvironment function just to see why plateminder was still using UTC:

`console.log(new Date().toString())`

And it produces:

`2023-05-11 11:06:13 Thu May 11 2023 16:06:13 GMT+0000 (Coordinated Universal Time)`

I'm running via docker desktop on windows 10 pro.

I originally mounted /etc/localtime but the system was still reporting UTC even though the windows 10 timezone was Central. 
 As a workaround I then set the mount to:

`- /usr/share/zoneinfo/US/Central:/etc/localtime:ro`

And the running container was finally showing CDT time:

```
$ date
Fri May 12 10:45:16 CDT 2023
$
```

After all this is when I finally was stumped as to why plateminder was still timestamping as UTC.

**Comment by sclaflin** [comment]
I did some looking yesterday evening, and it appears that using the host's /etc/localtime can cause issues if the host distribution doesn't match the container. What has been proven to work is setting a "TZ" environment variable for your container. I tested and confirmed this works for my docker containers.  Maybe give that a shot?

**Comment by wavecentral** [comment]
Setting the TZ environment variable worked and plateminder is using the right TZ set.

Interestingly, even with the system time showing CDT, that nodeJS still stayed UTC, but with putting TZ env variable, it finally took.

**Comment by wavecentral** [comment]
Works now.

**Comment by sclaflin** [comment]
I'll update documentation to reflect this. Glad it works!
