### ISSUE TITLE
Template Error in UNRAID app store

### ISSUE THREAD

**Issue by TRusselo** [sclaflin/Plate-Minder#29]
Tried to install from UNRAID app store. the docker template is managed by @digiblur 

the default template has errors:

maps container folder /app/data to host folder /appdata/plateminder/data
need to change container folder to /home/app/data 

also maps "file"  /app/config.yaml  to host /appdata/plateminder/config.yaml
this creates a folder called config.yaml  which cannot be written to. 
you must map the folder config.yaml is in, not the yaml itself.
also missing the /home  root folder of the container path.

This is how the mapping should look after correction
![image](https://github.com/sclaflin/Plate-Minder/assets/1154815/18f8e507-1b81-4bcf-a7ad-4b2a2fe0174f)

**Comment by sclaflin** [comment]
Hi there,

This isn't something I maintain. You may want to reach out @digiblur directly.

**Comment by TRusselo** [comment]
i have, but more leaving it here as a note to others who are trying and failing to getting it work on unraid.
THIS AINT ABOUT YOU!! lol. 
i just DM'd digiblur on that forum.

**Comment by sclaflin** [comment]
What a strange reason to edit a comment.  :-1:

**Comment by TRusselo** [comment]
i thought it would be funny. i laughed. good enough
