### ISSUE TITLE
I'm stuck

### ISSUE THREAD

**Issue by eethan-ethenet** [sclaflin/Plate-Minder#32]
Hello,

I have some questions and issues the config.yaml file, the plate detection, and the MQTT recorder.

How can I verify that the video is linked correctly? It would be nice to see the video feed or a still image every time I change the URL, so I can confirm that the video stream is being passed into Plate Minder.

Why does the config.yaml file lose all the OpenALPR code when I check it? I noticed this because I was trying to change the country code to “gb” (United Kingdom).

Why are no plates being detected or saved when cars with visible plates drive past? I checked the “images” and “data/images” folders, but they are empty. I also checked the database.db file, but there are no plates there either.

How can I connect to a MQTT recorder with the username (useruser23), password and URL (ca96bfa51866404197d2ccb35a05b215.s1.eu.hivemq.cloud)? The broker says “The client received no messages yet.”

Thank you for your assistance.

**Comment by sclaflin** [comment]
Hi!

Are you editing the config.yaml file manually or are you using Plate-Minder web? If you're editing config.yaml manually, make sure plate-minder isn't running while you do it.

Are there errors in the log output? That might give you some insights on what's going on.

The biggest reason for no plates being detected is the size and quality of the plates in the camera feed. I recommend taking a screenshot of the feed with a plate in it and upload it manually to the OpenALPR Wrapper container.  If you get output with plate information, the feed is likely good enough and you can look elsewhere to troubleshoot.

Please refer to the README.md file for an example of how to pass a username & password to an MQTT server.

**Comment by eethan-ethenet** [comment]
Thank for getting back to me

I have used a mix of both the editing the config.yaml and using the web (note: this is not downloaded from the "Plate Minder Web" Repo), 

I have confirmed that plate minder is running,

I think the reason for me not getting plate detected is because it's looking for USA Plates rather then UK Plates (I'm in England),

Could I use the file option to upload the screenshot?
here is a screenshot 
![CarRearMC16ZTB-090323-035045PM](https://github.com/sclaflin/Plate-Minder/assets/143966103/76af16fe-3e4d-448b-bed3-c526c61d8298)
here's a closeup shot
![Closeup-CarRear-MC16ZTB-090323-035045PM](https://github.com/sclaflin/Plate-Minder/assets/143966103/d150fe8c-1468-40ea-9669-e5c910a43f13)

The screenshot were taken using sniping tool

It may have been the case that this car was going too fast as the camera did lose focus,
here is video
[

https://github.com/sclaflin/Plate-Minder/assets/143966103/53cf6aa3-ca4d-4342-a7a5-703bbac20b70

]

**Comment by sclaflin** [comment]
If you can access the Open ALPR HTTP Wrapper container, you can upload the file yourself and see what it spits out. Here's what it should look like:

![image](https://github.com/sclaflin/Plate-Minder/assets/168424/1fe02bad-136c-4979-b2cc-e853d85622d0)

I took the liberty of uploading the still image you added above and it failed to recognize the plate in the frame.

Please note that I did not write OpenALPR. I just wrote an HTTP wrapper for it that Plate-Minder sends images to.

I suspect that the angle of the image is too skewed and distorted for OpenALPR to read.

**Comment by sclaflin** [comment]
I'm closing this issue since it's been a few weeks since I heard back from you. If you're still having trouble, let me know!
