### ISSUE TITLE
deploying the image using true nas scale

### ISSUE THREAD

**Issue by mosa2024** [sclaflin/Plate-Minder#33]
i tired to deploy the docker image using truenas scale , i got the following error

Failed to apply default image tag "https://github.com/sclaflin/Plate-Minder.git:latest": couldn't parse image reference "https://github.com/sclaflin/Plate-Minder.git:latest": invalid reference format: repository name must be lowercase

**Comment by sclaflin** [comment]
Hi there.  The docker images are available on docker hub, not github.

**Comment by mosa2024** [comment]
can you please add it to truenas scale docker apps or home assistant add on, alot of people need this but we aren't docker experts,
I'll try to pull from docker hub and let you know

**Comment by sclaflin** [comment]
If truenas scale supports docker images, I'd be shocked if it doesn't support pulling them from Docker Hub. I don't have any plans to specifically support truenas scale.

**Comment by mosa2024** [comment]
it does, i was able to pull the image from docker but it's not working, i'm by no means a docker expert. what about home assitant add on, any plan to do that ?
