### ISSUE TITLE
Best BlueIris Settings | method SETUP failed: 461 Unsupported transport

### ISSUE THREAD

**Issue by EmuLabs** [sclaflin/Plate-Minder#34]
Hi Dev thanks for your work. Can you advise what the best BlueIris encoder settings are? I am using the RTSP stream from BlueIris rather than connecting to the doorbell camera directly. 

![image](https://github.com/sclaflin/Plate-Minder/assets/105586721/5b739529-2881-40ec-b617-12c9d9f52a02)

![image](https://github.com/sclaflin/Plate-Minder/assets/105586721/5346b0d9-ebea-4803-9210-f093fd659d35)

Also I am getting this error: [rtsp @ 0x55810e760b00] method SETUP failed: 461 Unsupported transport. I have tried adding rtsp_transport and tcp as input args.

![image](https://github.com/sclaflin/Plate-Minder/assets/105586721/c3d74a21-5d75-4f2b-ba27-9d1765046f99)

However I can confirm that the connection is successful and the stream is being served

![image](https://github.com/sclaflin/Plate-Minder/assets/105586721/e35f53f4-85d8-4c9d-84ec-c89387d84e6e)

**Comment by sclaflin** [comment]
I have no experience with Blue Iris, so I can't provide specific advice.

However, PlateMinder is using the Jellyfin project's ffmpeg fork to read rtsp streams. The error you are seeing is coming from ffmpeg. The default ffmpeg command run by PlateMinder is:

```bash
ffmpeg -hide_banner -loglevel error -i "<YOUR URL>" -f mjpeg -q:v 4 -r 1/1 -an -
```

With the above, you should be better able to work out how to resolve your problem. Let me know how you get on!
