### ISSUE TITLE
Feature request: Source auto-restart

### ISSUE THREAD

**Issue by jseidl** [sclaflin/Plate-Minder#5]
Hi, one feature that would be extremely helpful would be auto-restart for sources when they crash/fail. 

My MJPEG source sometimes flick around and I have to manually restart the source. It would be awesome if it could be auto-restarted on failures. Maybe an option `auto_restart: True` paired with `max_retries: N`?

Sample errors I get:

```
http://<USER:PWD>@<ADDR>/mjpg/DrivewayLeft: Input/output error
...
[http @ 0x55ad52744b00] Stream ends prematurely at 111198147, should be 18446744073709551615 http://<USER:PWD>@<ADDR>/mjpg/DrivewayRight: Input/output error
```

LMK if you need more info regarding this.

**Comment by sclaflin** [comment]
Plate-Minder should already be doing this now. If FFMPEG exits with a non-zero exit code, the stream is restarted after a five second delay.  Did you see any logging similar to: "source failed"? It may be that there's an issue with your stream, but FFMPEG never exited.

**Comment by jseidl** [comment]
Hmmm weird. I'm using Plateminder-Web for debugging and I'm getting the stream occasionally crapping and not restarting by itself. I'd assume this is a scenario where ffmpeg exits with a non-zero EC and restarts but 🤷 still have to manually click on `Start Source` to get it going again

![image](https://user-images.githubusercontent.com/283041/153544467-9bdf7951-1814-4367-b1d6-614efa9fae2c.png)

**Comment by sclaflin** [comment]
Weird indeed. If you're not seeing "source failed" anywhere in your logs, it would seem that FFMPEG is exiting with a "0" exit code.

I can add an "alwaysRestart" config option that's off by default. Turning it on would have it restart regardless of exit code, which sounds like it would solve your problem. Downside would be that streams won't stay stopped when you manually stop them.

Thoughts?

**Comment by jseidl** [comment]
> I can add an "alwaysRestart" config option that's off by default. Turning it on would have it restart regardless of exit code, which sounds like it would solve your problem.

Yeap, sounds like it!

> Downside would be that streams won't stay stopped when you manually stop them.

That's OK, could be solved by having a toggle on `plateminder-web` next to the start/stop controls that would update the config and reload like the other config controls. Would that work? Not sure what other cases one would want to stop the source, maybe programmatically?

**Comment by sclaflin** [comment]
Added an 'alwaysRestart' option for sources. You'll need to re-pull sclaflin/plate-minder:latest and sclaflin/plate-minder-web:latest.

Let me know how it goes!

**Comment by jseidl** [comment]
Pulled, will let it you know! Thanks!

**Comment by jseidl** [comment]
Just to update, this seems to be working well so far! Thanks!
