### ISSUE TITLE
 Plate-Minder runs as user id 1000

### ISSUE THREAD

**Issue by Davo-Exp4** [sclaflin/Plate-Minder#8]
Cannot start the container, problem occurs with node here is the output related with user id

![image](https://user-images.githubusercontent.com/34872306/155181764-b22838f7-fd87-4e3c-a8ad-1fb826ea5173.png)

![image](https://user-images.githubusercontent.com/34872306/155181853-f8c0a3fb-c546-4009-bc77-37c2caef6902.png)

**Comment by sclaflin** [comment]
Hey there,

Please see the following: https://github.com/sclaflin/Plate-Minder#common-problems
